- id: connect-manifest
  name: Connect write manifest
  description: "Create a manifest file for Posit Connect deployment"
  entry: rsconnect write-manifest
  language: python
  args: [--overwrite]
  require_serial: true
  additional_dependencies: []
  minimum_pre_commit_version: "2.9.2"
